apiVersion: apps/v1
kind: Deployment
metadata:
  name: samplefinalcheck-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: SampleFinalCheck
  template:
    metadata:
      labels:
        app: SampleFinalCheck
    spec:
      containers:
      - name: samplefinalcheckrepos
        image: samplecr.azurecr.io/samplefinalcheckrepos:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: dsconfigsn

---
apiVersion: v1
kind: Service
metadata:
  name: samplefinalcheck
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: SampleFinalCheck